package com.xxdai.filter.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2017-02-16T16:34:32.388+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://webservice.batch.xxdai.com/", name = "UserDimensionCXFService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserDimensionCXFService {

    @RequestWrapper(localName = "putUserDimensionToIO", targetNamespace = "http://webservice.batch.xxdai.com/", className = "com.xxdai.filter.ws.PutUserDimensionToIO")
    @WebMethod
    @ResponseWrapper(localName = "putUserDimensionToIOResponse", targetNamespace = "http://webservice.batch.xxdai.com/", className = "com.xxdai.filter.ws.PutUserDimensionToIOResponse")
    public void putUserDimensionToIO();

    @RequestWrapper(localName = "putUserIdToRedis", targetNamespace = "http://webservice.batch.xxdai.com/", className = "com.xxdai.filter.ws.PutUserIdToRedis")
    @WebMethod
    @ResponseWrapper(localName = "putUserIdToRedisResponse", targetNamespace = "http://webservice.batch.xxdai.com/", className = "com.xxdai.filter.ws.PutUserIdToRedisResponse")
    public void putUserIdToRedis(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );
}
