package com.xxdai.filter.ws;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2017-02-16T16:34:32.431+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebServiceClient(name = "UserDimensionCXFServiceImplService", 
                  wsdlLocation = "http://localhost:8080/v6_webservice/service/userDimensionWebService?wsdl",
                  targetNamespace = "http://impl.webservice.batch.xxdai.com/") 
public class UserDimensionCXFServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.batch.xxdai.com/", "UserDimensionCXFServiceImplService");
    public final static QName UserDimensionCXFServiceImplPort = new QName("http://impl.webservice.batch.xxdai.com/", "UserDimensionCXFServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/v6_webservice/service/userDimensionWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserDimensionCXFServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/v6_webservice/service/userDimensionWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserDimensionCXFServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserDimensionCXFServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserDimensionCXFServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns UserDimensionCXFService
     */
    @WebEndpoint(name = "UserDimensionCXFServiceImplPort")
    public UserDimensionCXFService getUserDimensionCXFServiceImplPort() {
        return super.getPort(UserDimensionCXFServiceImplPort, UserDimensionCXFService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserDimensionCXFService
     */
    @WebEndpoint(name = "UserDimensionCXFServiceImplPort")
    public UserDimensionCXFService getUserDimensionCXFServiceImplPort(WebServiceFeature... features) {
        return super.getPort(UserDimensionCXFServiceImplPort, UserDimensionCXFService.class, features);
    }

}
