package com.xxdai.person.ws.infos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-08-28T15:40:16.321+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://interfaces.webService.xxdai.com/", name = "InfosCXFService")
@XmlSeeAlso({ObjectFactory.class})
public interface InfosCXFService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addInfos", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.infos.AddInfos")
    @WebMethod
    @ResponseWrapper(localName = "addInfosResponse", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.infos.AddInfosResponse")
    public java.lang.String addInfos(
        @WebParam(name = "addInfosReqJson", targetNamespace = "")
        java.lang.String addInfosReqJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateInfos", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.infos.UpdateInfos")
    @WebMethod
    @ResponseWrapper(localName = "updateInfosResponse", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.infos.UpdateInfosResponse")
    public java.lang.String updateInfos(
        @WebParam(name = "updateInfosReqJson", targetNamespace = "")
        java.lang.String updateInfosReqJson
    );
}
