package com.xxdai.person.ws.infos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-08-28T15:40:16.352+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebServiceClient(name = "InfosCXFServiceImplService", 
                  wsdlLocation = "http://localhost:8080/v6_front/service/infosWebService?wsdl",
                  targetNamespace = "http://impl.webService.xxdai.com/") 
public class InfosCXFServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webService.xxdai.com/", "InfosCXFServiceImplService");
    public final static QName InfosCXFServiceImplPort = new QName("http://impl.webService.xxdai.com/", "InfosCXFServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/v6_front/service/infosWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InfosCXFServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/v6_front/service/infosWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public InfosCXFServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InfosCXFServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InfosCXFServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns InfosCXFService
     */
    @WebEndpoint(name = "InfosCXFServiceImplPort")
    public InfosCXFService getInfosCXFServiceImplPort() {
        return super.getPort(InfosCXFServiceImplPort, InfosCXFService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InfosCXFService
     */
    @WebEndpoint(name = "InfosCXFServiceImplPort")
    public InfosCXFService getInfosCXFServiceImplPort(WebServiceFeature... features) {
        return super.getPort(InfosCXFServiceImplPort, InfosCXFService.class, features);
    }

}
