package com.xxdai.seo.ws.adproduct;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-12-24T09:54:09.599+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://webservice.seo.xxdai.com/", name = "SeoAdProductCXFService")
@XmlSeeAlso({ObjectFactory.class})
public interface SeoAdProductCXFService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveOrUpdateAdProduct", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.adproduct.SaveOrUpdateAdProduct")
    @WebMethod
    @ResponseWrapper(localName = "saveOrUpdateAdProductResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.adproduct.SaveOrUpdateAdProductResponse")
    public java.lang.String saveOrUpdateAdProduct(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectPageAdProduct", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.adproduct.SelectPageAdProduct")
    @WebMethod
    @ResponseWrapper(localName = "selectPageAdProductResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.adproduct.SelectPageAdProductResponse")
    public java.lang.String selectPageAdProduct(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectAdProduct", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.adproduct.SelectAdProduct")
    @WebMethod
    @ResponseWrapper(localName = "selectAdProductResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.adproduct.SelectAdProductResponse")
    public java.lang.String selectAdProduct(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSeoAdProductById", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.adproduct.GetSeoAdProductById")
    @WebMethod
    @ResponseWrapper(localName = "getSeoAdProductByIdResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.adproduct.GetSeoAdProductByIdResponse")
    public java.lang.String getSeoAdProductById(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteAdProduct", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.adproduct.DeleteAdProduct")
    @WebMethod
    @ResponseWrapper(localName = "deleteAdProductResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.adproduct.DeleteAdProductResponse")
    public java.lang.String deleteAdProduct(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );
}
