package com.xxdai.seo.ws.adproduct;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-12-24T09:54:09.709+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebServiceClient(name = "SeoAdProductCXFServiceImplService", 
                  wsdlLocation = "http://localhost:8080/v6_webservice/service/seoAdProductWebService?wsdl",
                  targetNamespace = "http://impl.webservice.seo.xxdai.com/") 
public class SeoAdProductCXFServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.seo.xxdai.com/", "SeoAdProductCXFServiceImplService");
    public final static QName SeoAdProductCXFServiceImplPort = new QName("http://impl.webservice.seo.xxdai.com/", "SeoAdProductCXFServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/v6_webservice/service/seoAdProductWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SeoAdProductCXFServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/v6_webservice/service/seoAdProductWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SeoAdProductCXFServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SeoAdProductCXFServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SeoAdProductCXFServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SeoAdProductCXFService
     */
    @WebEndpoint(name = "SeoAdProductCXFServiceImplPort")
    public SeoAdProductCXFService getSeoAdProductCXFServiceImplPort() {
        return super.getPort(SeoAdProductCXFServiceImplPort, SeoAdProductCXFService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SeoAdProductCXFService
     */
    @WebEndpoint(name = "SeoAdProductCXFServiceImplPort")
    public SeoAdProductCXFService getSeoAdProductCXFServiceImplPort(WebServiceFeature... features) {
        return super.getPort(SeoAdProductCXFServiceImplPort, SeoAdProductCXFService.class, features);
    }

}
