package com.xxdai.person.ws.realname;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-03T09:35:49.402+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebServiceClient(name = "ApproCXFServiceImpService", 
                  wsdlLocation = "http://localhost:8080/v6_webservice/service/approCXFService?wsdl",
                  targetNamespace = "http://appro.impl.webService.xxdai.com/") 
public class ApproCXFServiceImpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://appro.impl.webService.xxdai.com/", "ApproCXFServiceImpService");
    public final static QName ApproCXFServiceImpPort = new QName("http://appro.impl.webService.xxdai.com/", "ApproCXFServiceImpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/v6_webservice/service/approCXFService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ApproCXFServiceImpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/v6_webservice/service/approCXFService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ApproCXFServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ApproCXFServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApproCXFServiceImpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ApproCXFService
     */
    @WebEndpoint(name = "ApproCXFServiceImpPort")
    public ApproCXFService getApproCXFServiceImpPort() {
        return super.getPort(ApproCXFServiceImpPort, ApproCXFService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ApproCXFService
     */
    @WebEndpoint(name = "ApproCXFServiceImpPort")
    public ApproCXFService getApproCXFServiceImpPort(WebServiceFeature... features) {
        return super.getPort(ApproCXFServiceImpPort, ApproCXFService.class, features);
    }

}
