package com.xxdai.person.ws.realname;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-03T09:54:48.957+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://appro.interfaces.webService.xxdai.com/", name = "ApproQueryCXFService")
@XmlSeeAlso({ObjectFactory.class})
public interface ApproQueryCXFService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryRealNameApproByUserId", targetNamespace = "http://appro.interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.realname.QueryRealNameApproByUserId")
    @WebMethod
    @ResponseWrapper(localName = "queryRealNameApproByUserIdResponse", targetNamespace = "http://appro.interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.realname.QueryRealNameApproByUserIdResponse")
    public java.lang.String queryRealNameApproByUserId(
        @WebParam(name = "userJson", targetNamespace = "")
        java.lang.String userJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryMobileApproByPhotoNum", targetNamespace = "http://appro.interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.realname.QueryMobileApproByPhotoNum")
    @WebMethod
    @ResponseWrapper(localName = "queryMobileApproByPhotoNumResponse", targetNamespace = "http://appro.interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.realname.QueryMobileApproByPhotoNumResponse")
    public java.lang.String queryMobileApproByPhotoNum(
        @WebParam(name = "numJson", targetNamespace = "")
        java.lang.String numJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryVipApproEmployeeNum", targetNamespace = "http://appro.interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.realname.QueryVipApproEmployeeNum")
    @WebMethod
    @ResponseWrapper(localName = "queryVipApproEmployeeNumResponse", targetNamespace = "http://appro.interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.realname.QueryVipApproEmployeeNumResponse")
    public java.lang.String queryVipApproEmployeeNum(
        @WebParam(name = "jobNum", targetNamespace = "")
        java.lang.String jobNum
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryMobileApproByUserId", targetNamespace = "http://appro.interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.realname.QueryMobileApproByUserId")
    @WebMethod
    @ResponseWrapper(localName = "queryMobileApproByUserIdResponse", targetNamespace = "http://appro.interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.realname.QueryMobileApproByUserIdResponse")
    public java.lang.String queryMobileApproByUserId(
        @WebParam(name = "userIdJson", targetNamespace = "")
        java.lang.String userIdJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryEmailApproByUserId", targetNamespace = "http://appro.interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.realname.QueryEmailApproByUserId")
    @WebMethod
    @ResponseWrapper(localName = "queryEmailApproByUserIdResponse", targetNamespace = "http://appro.interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.realname.QueryEmailApproByUserIdResponse")
    public java.lang.String queryEmailApproByUserId(
        @WebParam(name = "userIdJson", targetNamespace = "")
        java.lang.String userIdJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryRealNameApproById", targetNamespace = "http://appro.interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.realname.QueryRealNameApproById")
    @WebMethod
    @ResponseWrapper(localName = "queryRealNameApproByIdResponse", targetNamespace = "http://appro.interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.realname.QueryRealNameApproByIdResponse")
    public java.lang.String queryRealNameApproById(
        @WebParam(name = "idJson", targetNamespace = "")
        java.lang.String idJson
    );
}
