
package com.xxdai.seo.ws.info;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.12
 * 2015-01-23T10:32:18.663+08:00
 * Generated source version: 2.7.12
 */

@WebFault(name = "DaoException", targetNamespace = "http://webservice.seo.xxdai.com/")
public class DaoException_Exception extends Exception {
    
    private com.xxdai.seo.ws.info.DaoException daoException;

    public DaoException_Exception() {
        super();
    }
    
    public DaoException_Exception(String message) {
        super(message);
    }
    
    public DaoException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public DaoException_Exception(String message, com.xxdai.seo.ws.info.DaoException daoException) {
        super(message);
        this.daoException = daoException;
    }

    public DaoException_Exception(String message, com.xxdai.seo.ws.info.DaoException daoException, Throwable cause) {
        super(message, cause);
        this.daoException = daoException;
    }

    public com.xxdai.seo.ws.info.DaoException getFaultInfo() {
        return this.daoException;
    }
}
