package com.xxdai.seo.ws.info;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2015-01-23T10:32:18.835+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebServiceClient(name = "SeoInfoCXFServiceImplService", 
                  wsdlLocation = "http://localhost:8080/v6_webservice/service/seoInfoWebService?wsdl",
                  targetNamespace = "http://impl.webservice.seo.xxdai.com/") 
public class SeoInfoCXFServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.seo.xxdai.com/", "SeoInfoCXFServiceImplService");
    public final static QName SeoInfoCXFServiceImplPort = new QName("http://impl.webservice.seo.xxdai.com/", "SeoInfoCXFServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/v6_webservice/service/seoInfoWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SeoInfoCXFServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/v6_webservice/service/seoInfoWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SeoInfoCXFServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SeoInfoCXFServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SeoInfoCXFServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SeoInfoCXFService
     */
    @WebEndpoint(name = "SeoInfoCXFServiceImplPort")
    public SeoInfoCXFService getSeoInfoCXFServiceImplPort() {
        return super.getPort(SeoInfoCXFServiceImplPort, SeoInfoCXFService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SeoInfoCXFService
     */
    @WebEndpoint(name = "SeoInfoCXFServiceImplPort")
    public SeoInfoCXFService getSeoInfoCXFServiceImplPort(WebServiceFeature... features) {
        return super.getPort(SeoInfoCXFServiceImplPort, SeoInfoCXFService.class, features);
    }

}
