package com.xxdai.seo.ws.info;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2015-01-23T10:32:18.757+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://webservice.seo.xxdai.com/", name = "SeoInfoCXFService")
@XmlSeeAlso({ObjectFactory.class})
public interface SeoInfoCXFService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRandomTags", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetRandomTags")
    @WebMethod
    @ResponseWrapper(localName = "getRandomTagsResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetRandomTagsResponse")
    public java.lang.String getRandomTags(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSecondInfoTagsByHot", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetSecondInfoTagsByHot")
    @WebMethod
    @ResponseWrapper(localName = "getSecondInfoTagsByHotResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetSecondInfoTagsByHotResponse")
    public java.lang.String getSecondInfoTagsByHot(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getInfoListByTags", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetInfoListByTags")
    @WebMethod
    @ResponseWrapper(localName = "getInfoListByTagsResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetInfoListByTagsResponse")
    public java.lang.String getInfoListByTags(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getNextTagsById", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetNextTagsById")
    @WebMethod
    @ResponseWrapper(localName = "getNextTagsByIdResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetNextTagsByIdResponse")
    public java.lang.String getNextTagsById(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getInfoByInfoId", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetInfoByInfoId")
    @WebMethod
    @ResponseWrapper(localName = "getInfoByInfoIdResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetInfoByInfoIdResponse")
    public java.lang.String getInfoByInfoId(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "ListGetByCateID", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.ListGetByCateID")
    @WebMethod(operationName = "ListGetByCateID")
    @ResponseWrapper(localName = "ListGetByCateIDResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.ListGetByCateIDResponse")
    public java.lang.String listGetByCateID(
        @WebParam(name = "paramsjson", targetNamespace = "")
        java.lang.String paramsjson
    ) throws DaoException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryarticleByID", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.QueryarticleByID")
    @WebMethod
    @ResponseWrapper(localName = "queryarticleByIDResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.QueryarticleByIDResponse")
    public java.lang.String queryarticleByID(
        @WebParam(name = "paramJson", targetNamespace = "")
        java.lang.String paramJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getInfoListByCateId", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetInfoListByCateId")
    @WebMethod
    @ResponseWrapper(localName = "getInfoListByCateIdResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetInfoListByCateIdResponse")
    public java.lang.String getInfoListByCateId(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSecondHotInfoByHot", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetSecondHotInfoByHot")
    @WebMethod
    @ResponseWrapper(localName = "getSecondHotInfoByHotResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetSecondHotInfoByHotResponse")
    public java.lang.String getSecondHotInfoByHot(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryPageDicCommon", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.QueryPageDicCommon")
    @WebMethod
    @ResponseWrapper(localName = "queryPageDicCommonResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.QueryPageDicCommonResponse")
    public java.lang.String queryPageDicCommon(
        @WebParam(name = "queryParam", targetNamespace = "")
        java.lang.String queryParam
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSeoInfoListByTags", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetSeoInfoListByTags")
    @WebMethod
    @ResponseWrapper(localName = "getSeoInfoListByTagsResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetSeoInfoListByTagsResponse")
    public java.lang.String getSeoInfoListByTags(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getInfosByTags", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetInfosByTags")
    @WebMethod
    @ResponseWrapper(localName = "getInfosByTagsResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetInfosByTagsResponse")
    public java.lang.String getInfosByTags(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSecondHotInfoByBaidu", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetSecondHotInfoByBaidu")
    @WebMethod
    @ResponseWrapper(localName = "getSecondHotInfoByBaiduResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetSecondHotInfoByBaiduResponse")
    public java.lang.String getSecondHotInfoByBaidu(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSecondInfoByHot", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetSecondInfoByHot")
    @WebMethod
    @ResponseWrapper(localName = "getSecondInfoByHotResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetSecondInfoByHotResponse")
    public java.lang.String getSecondInfoByHot(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryObjectByIdDic", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.QueryObjectByIdDic")
    @WebMethod
    @ResponseWrapper(localName = "queryObjectByIdDicResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.QueryObjectByIdDicResponse")
    public java.lang.String queryObjectByIdDic(
        @WebParam(name = "queryId", targetNamespace = "")
        java.lang.String queryId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveSeoInfo", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.SaveSeoInfo")
    @WebMethod
    @ResponseWrapper(localName = "saveSeoInfoResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.SaveSeoInfoResponse")
    public java.lang.String saveSeoInfo(
        @WebParam(name = "paramJson", targetNamespace = "")
        java.lang.String paramJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTagsById", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetTagsById")
    @WebMethod
    @ResponseWrapper(localName = "getTagsByIdResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetTagsByIdResponse")
    public java.lang.String getTagsById(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFirstInfoByHot", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetFirstInfoByHot")
    @WebMethod
    @ResponseWrapper(localName = "getFirstInfoByHotResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetFirstInfoByHotResponse")
    public java.lang.String getFirstInfoByHot(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateSeoInfoStatus", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.UpdateSeoInfoStatus")
    @WebMethod
    @ResponseWrapper(localName = "updateSeoInfoStatusResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.UpdateSeoInfoStatusResponse")
    public java.lang.String updateSeoInfoStatus(
        @WebParam(name = "paramJson", targetNamespace = "")
        java.lang.String paramJson
    ) throws DaoException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFirstInfoTagsByHot", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetFirstInfoTagsByHot")
    @WebMethod
    @ResponseWrapper(localName = "getFirstInfoTagsByHotResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetFirstInfoTagsByHotResponse")
    public java.lang.String getFirstInfoTagsByHot(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryArticleList", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.QueryArticleList")
    @WebMethod
    @ResponseWrapper(localName = "queryArticleListResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.QueryArticleListResponse")
    public java.lang.String queryArticleList(
        @WebParam(name = "paramsjson", targetNamespace = "")
        java.lang.String paramsjson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getNextInfosByInfoId", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetNextInfosByInfoId")
    @WebMethod
    @ResponseWrapper(localName = "getNextInfosByInfoIdResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.info.GetNextInfosByInfoIdResponse")
    public java.lang.String getNextInfosByInfoId(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );
}
