
package com.xxdai.news.webservice.interfaces;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-10-17T17:39:04.472+08:00
 * Generated source version: 2.7.18
 * 
 */
 
public class NewsCXFService_NewsCXFServiceImpPort_Server{

    protected NewsCXFService_NewsCXFServiceImpPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new NewsCXFServiceImpl();
        String address = "http://test.xxd.com/yx_service/service/newsWebService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new NewsCXFService_NewsCXFServiceImpPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
