
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.xxdai.news.webservice.interfaces;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-10-17T17:39:04.440+08:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "NewsCXFServiceImpService",
                      portName = "NewsCXFServiceImpPort",
                      targetNamespace = "http://impl.webService.news.xxdai.com/",
                      wsdlLocation = "http://test.xxd.com/yx_service/service/newsWebService?wsdl",
                      endpointInterface = "com.xxdai.news.webservice.interfaces.NewsCXFService")
                      
public class NewsCXFServiceImpl implements NewsCXFService {

    private static final Logger LOG = Logger.getLogger(NewsCXFServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.xxdai.news.webservice.interfaces.NewsCXFService#queryNewsPptById(java.lang.String  newsPptJson )*
     */
    public java.lang.String queryNewsPptById(java.lang.String newsPptJson) { 
        LOG.info("Executing operation queryNewsPptById");
        System.out.println(newsPptJson);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xxdai.news.webservice.interfaces.NewsCXFService#checkFileNameOnly(java.lang.String  params )*
     */
    public java.lang.String checkFileNameOnly(java.lang.String params) { 
        LOG.info("Executing operation checkFileNameOnly");
        System.out.println(params);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xxdai.news.webservice.interfaces.NewsCXFService#delNewsPpt(java.lang.String  newsPptJson )*
     */
    public java.lang.String delNewsPpt(java.lang.String newsPptJson) { 
        LOG.info("Executing operation delNewsPpt");
        System.out.println(newsPptJson);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xxdai.news.webservice.interfaces.NewsCXFService#delLinkExchange(java.lang.String  linkJson )*
     */
    public java.lang.String delLinkExchange(java.lang.String linkJson) { 
        LOG.info("Executing operation delLinkExchange");
        System.out.println(linkJson);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xxdai.news.webservice.interfaces.NewsCXFService#saveNewsPpt(java.lang.String  newsPptJson )*
     */
    public java.lang.String saveNewsPpt(java.lang.String newsPptJson) { 
        LOG.info("Executing operation saveNewsPpt");
        System.out.println(newsPptJson);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xxdai.news.webservice.interfaces.NewsCXFService#queryNewsPptList(java.lang.String  newsPptJson )*
     */
    public java.lang.String queryNewsPptList(java.lang.String newsPptJson) { 
        LOG.info("Executing operation queryNewsPptList");
        System.out.println(newsPptJson);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xxdai.news.webservice.interfaces.NewsCXFService#saveNewsNotices(java.lang.String  newsNoticesJson )*
     */
    public java.lang.String saveNewsNotices(java.lang.String newsNoticesJson) { 
        LOG.info("Executing operation saveNewsNotices");
        System.out.println(newsNoticesJson);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xxdai.news.webservice.interfaces.NewsCXFService#queryNewsNoticesById(java.lang.String  newsNoticesJson )*
     */
    public java.lang.String queryNewsNoticesById(java.lang.String newsNoticesJson) { 
        LOG.info("Executing operation queryNewsNoticesById");
        System.out.println(newsNoticesJson);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xxdai.news.webservice.interfaces.NewsCXFService#queryLinkExchangeById(java.lang.String  linkJson )*
     */
    public java.lang.String queryLinkExchangeById(java.lang.String linkJson) { 
        LOG.info("Executing operation queryLinkExchangeById");
        System.out.println(linkJson);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xxdai.news.webservice.interfaces.NewsCXFService#delNewsNotices(java.lang.String  newsNoticesJson )*
     */
    public java.lang.String delNewsNotices(java.lang.String newsNoticesJson) { 
        LOG.info("Executing operation delNewsNotices");
        System.out.println(newsNoticesJson);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xxdai.news.webservice.interfaces.NewsCXFService#queryNewsPptByPosition(java.lang.String  params )*
     */
    public java.lang.String queryNewsPptByPosition(java.lang.String params) { 
        LOG.info("Executing operation queryNewsPptByPosition");
        System.out.println(params);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xxdai.news.webservice.interfaces.NewsCXFService#queryLinkExchangeListForFrontFriend(java.lang.String  linkJson )*
     */
    public java.lang.String queryLinkExchangeListForFrontFriend(java.lang.String linkJson) { 
        LOG.info("Executing operation queryLinkExchangeListForFrontFriend");
        System.out.println(linkJson);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xxdai.news.webservice.interfaces.NewsCXFService#queryLinkExchangeListForFrontPartner(java.lang.String  linkJson )*
     */
    public java.lang.String queryLinkExchangeListForFrontPartner(java.lang.String linkJson) { 
        LOG.info("Executing operation queryLinkExchangeListForFrontPartner");
        System.out.println(linkJson);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xxdai.news.webservice.interfaces.NewsCXFService#queryNewsNotices(java.lang.String  newsNoticesJson )*
     */
    public java.lang.String queryNewsNotices(java.lang.String newsNoticesJson) { 
        LOG.info("Executing operation queryNewsNotices");
        System.out.println(newsNoticesJson);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xxdai.news.webservice.interfaces.NewsCXFService#queryNewsPptListByFront(java.lang.String  newsPptJson )*
     */
    public java.lang.String queryNewsPptListByFront(java.lang.String newsPptJson) { 
        LOG.info("Executing operation queryNewsPptListByFront");
        System.out.println(newsPptJson);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xxdai.news.webservice.interfaces.NewsCXFService#queryLinkExchangeList(java.lang.String  linkJson )*
     */
    public java.lang.String queryLinkExchangeList(java.lang.String linkJson) { 
        LOG.info("Executing operation queryLinkExchangeList");
        System.out.println(linkJson);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xxdai.news.webservice.interfaces.NewsCXFService#saveLinkExchange(java.lang.String  linkJson )*
     */
    public java.lang.String saveLinkExchange(java.lang.String linkJson) { 
        LOG.info("Executing operation saveLinkExchange");
        System.out.println(linkJson);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xxdai.news.webservice.interfaces.NewsCXFService#queryNewsNoticesListForFront(java.lang.String  newsNoticesJson )*
     */
    public java.lang.String queryNewsNoticesListForFront(java.lang.String newsNoticesJson) { 
        LOG.info("Executing operation queryNewsNoticesListForFront");
        System.out.println(newsNoticesJson);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
