
package com.xxdai.news.webservice.interfaces;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-10-17T17:39:04.369+08:00
 * Generated source version: 2.7.18
 * 
 */
public final class NewsCXFService_NewsCXFServiceImpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.webService.news.xxdai.com/", "NewsCXFServiceImpService");

    private NewsCXFService_NewsCXFServiceImpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = NewsCXFServiceImpService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        NewsCXFServiceImpService ss = new NewsCXFServiceImpService(wsdlURL, SERVICE_NAME);
        NewsCXFService port = ss.getNewsCXFServiceImpPort();  
        
        {
        System.out.println("Invoking queryNewsPptById...");
        java.lang.String _queryNewsPptById_newsPptJson = "";
        java.lang.String _queryNewsPptById__return = port.queryNewsPptById(_queryNewsPptById_newsPptJson);
        System.out.println("queryNewsPptById.result=" + _queryNewsPptById__return);


        }
        {
        System.out.println("Invoking checkFileNameOnly...");
        java.lang.String _checkFileNameOnly_params = "";
        java.lang.String _checkFileNameOnly__return = port.checkFileNameOnly(_checkFileNameOnly_params);
        System.out.println("checkFileNameOnly.result=" + _checkFileNameOnly__return);


        }
        {
        System.out.println("Invoking delNewsPpt...");
        java.lang.String _delNewsPpt_newsPptJson = "";
        java.lang.String _delNewsPpt__return = port.delNewsPpt(_delNewsPpt_newsPptJson);
        System.out.println("delNewsPpt.result=" + _delNewsPpt__return);


        }
        {
        System.out.println("Invoking delLinkExchange...");
        java.lang.String _delLinkExchange_linkJson = "";
        java.lang.String _delLinkExchange__return = port.delLinkExchange(_delLinkExchange_linkJson);
        System.out.println("delLinkExchange.result=" + _delLinkExchange__return);


        }
        {
        System.out.println("Invoking saveNewsPpt...");
        java.lang.String _saveNewsPpt_newsPptJson = "";
        java.lang.String _saveNewsPpt__return = port.saveNewsPpt(_saveNewsPpt_newsPptJson);
        System.out.println("saveNewsPpt.result=" + _saveNewsPpt__return);


        }
        {
        System.out.println("Invoking queryNewsPptList...");
        java.lang.String _queryNewsPptList_newsPptJson = "";
        java.lang.String _queryNewsPptList__return = port.queryNewsPptList(_queryNewsPptList_newsPptJson);
        System.out.println("queryNewsPptList.result=" + _queryNewsPptList__return);


        }
        {
        System.out.println("Invoking saveNewsNotices...");
        java.lang.String _saveNewsNotices_newsNoticesJson = "";
        java.lang.String _saveNewsNotices__return = port.saveNewsNotices(_saveNewsNotices_newsNoticesJson);
        System.out.println("saveNewsNotices.result=" + _saveNewsNotices__return);


        }
        {
        System.out.println("Invoking queryNewsNoticesById...");
        java.lang.String _queryNewsNoticesById_newsNoticesJson = "";
        java.lang.String _queryNewsNoticesById__return = port.queryNewsNoticesById(_queryNewsNoticesById_newsNoticesJson);
        System.out.println("queryNewsNoticesById.result=" + _queryNewsNoticesById__return);


        }
        {
        System.out.println("Invoking queryLinkExchangeById...");
        java.lang.String _queryLinkExchangeById_linkJson = "";
        java.lang.String _queryLinkExchangeById__return = port.queryLinkExchangeById(_queryLinkExchangeById_linkJson);
        System.out.println("queryLinkExchangeById.result=" + _queryLinkExchangeById__return);


        }
        {
        System.out.println("Invoking delNewsNotices...");
        java.lang.String _delNewsNotices_newsNoticesJson = "";
        java.lang.String _delNewsNotices__return = port.delNewsNotices(_delNewsNotices_newsNoticesJson);
        System.out.println("delNewsNotices.result=" + _delNewsNotices__return);


        }
        {
        System.out.println("Invoking queryNewsPptByPosition...");
        java.lang.String _queryNewsPptByPosition_params = "";
        java.lang.String _queryNewsPptByPosition__return = port.queryNewsPptByPosition(_queryNewsPptByPosition_params);
        System.out.println("queryNewsPptByPosition.result=" + _queryNewsPptByPosition__return);


        }
        {
        System.out.println("Invoking queryLinkExchangeListForFrontFriend...");
        java.lang.String _queryLinkExchangeListForFrontFriend_linkJson = "";
        java.lang.String _queryLinkExchangeListForFrontFriend__return = port.queryLinkExchangeListForFrontFriend(_queryLinkExchangeListForFrontFriend_linkJson);
        System.out.println("queryLinkExchangeListForFrontFriend.result=" + _queryLinkExchangeListForFrontFriend__return);


        }
        {
        System.out.println("Invoking queryLinkExchangeListForFrontPartner...");
        java.lang.String _queryLinkExchangeListForFrontPartner_linkJson = "";
        java.lang.String _queryLinkExchangeListForFrontPartner__return = port.queryLinkExchangeListForFrontPartner(_queryLinkExchangeListForFrontPartner_linkJson);
        System.out.println("queryLinkExchangeListForFrontPartner.result=" + _queryLinkExchangeListForFrontPartner__return);


        }
        {
        System.out.println("Invoking queryNewsNotices...");
        java.lang.String _queryNewsNotices_newsNoticesJson = "";
        java.lang.String _queryNewsNotices__return = port.queryNewsNotices(_queryNewsNotices_newsNoticesJson);
        System.out.println("queryNewsNotices.result=" + _queryNewsNotices__return);


        }
        {
        System.out.println("Invoking queryNewsPptListByFront...");
        java.lang.String _queryNewsPptListByFront_newsPptJson = "";
        java.lang.String _queryNewsPptListByFront__return = port.queryNewsPptListByFront(_queryNewsPptListByFront_newsPptJson);
        System.out.println("queryNewsPptListByFront.result=" + _queryNewsPptListByFront__return);


        }
        {
        System.out.println("Invoking queryLinkExchangeList...");
        java.lang.String _queryLinkExchangeList_linkJson = "";
        java.lang.String _queryLinkExchangeList__return = port.queryLinkExchangeList(_queryLinkExchangeList_linkJson);
        System.out.println("queryLinkExchangeList.result=" + _queryLinkExchangeList__return);


        }
        {
        System.out.println("Invoking saveLinkExchange...");
        java.lang.String _saveLinkExchange_linkJson = "";
        java.lang.String _saveLinkExchange__return = port.saveLinkExchange(_saveLinkExchange_linkJson);
        System.out.println("saveLinkExchange.result=" + _saveLinkExchange__return);


        }
        {
        System.out.println("Invoking queryNewsNoticesListForFront...");
        java.lang.String _queryNewsNoticesListForFront_newsNoticesJson = "";
        java.lang.String _queryNewsNoticesListForFront__return = port.queryNewsNoticesListForFront(_queryNewsNoticesListForFront_newsNoticesJson);
        System.out.println("queryNewsNoticesListForFront.result=" + _queryNewsNoticesListForFront__return);


        }

        System.exit(0);
    }

}
