package com.xxdai.news.webservice.interfaces;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-10-17T17:39:04.459+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://Interfaces.webService.news.xxdai.com/", name = "NewsCXFService")
@XmlSeeAlso({ObjectFactory.class})
public interface NewsCXFService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryNewsPptById", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.QueryNewsPptById")
    @WebMethod
    @ResponseWrapper(localName = "queryNewsPptByIdResponse", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.QueryNewsPptByIdResponse")
    public java.lang.String queryNewsPptById(
        @WebParam(name = "newsPptJson", targetNamespace = "")
        java.lang.String newsPptJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkFileNameOnly", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.CheckFileNameOnly")
    @WebMethod
    @ResponseWrapper(localName = "checkFileNameOnlyResponse", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.CheckFileNameOnlyResponse")
    public java.lang.String checkFileNameOnly(
        @WebParam(name = "params", targetNamespace = "")
        java.lang.String params
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "delNewsPpt", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.DelNewsPpt")
    @WebMethod
    @ResponseWrapper(localName = "delNewsPptResponse", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.DelNewsPptResponse")
    public java.lang.String delNewsPpt(
        @WebParam(name = "newsPptJson", targetNamespace = "")
        java.lang.String newsPptJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "delLinkExchange", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.DelLinkExchange")
    @WebMethod
    @ResponseWrapper(localName = "delLinkExchangeResponse", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.DelLinkExchangeResponse")
    public java.lang.String delLinkExchange(
        @WebParam(name = "linkJson", targetNamespace = "")
        java.lang.String linkJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveNewsPpt", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.SaveNewsPpt")
    @WebMethod
    @ResponseWrapper(localName = "saveNewsPptResponse", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.SaveNewsPptResponse")
    public java.lang.String saveNewsPpt(
        @WebParam(name = "newsPptJson", targetNamespace = "")
        java.lang.String newsPptJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryNewsPptList", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.QueryNewsPptList")
    @WebMethod
    @ResponseWrapper(localName = "queryNewsPptListResponse", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.QueryNewsPptListResponse")
    public java.lang.String queryNewsPptList(
        @WebParam(name = "newsPptJson", targetNamespace = "")
        java.lang.String newsPptJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveNewsNotices", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.SaveNewsNotices")
    @WebMethod
    @ResponseWrapper(localName = "saveNewsNoticesResponse", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.SaveNewsNoticesResponse")
    public java.lang.String saveNewsNotices(
        @WebParam(name = "newsNoticesJson", targetNamespace = "")
        java.lang.String newsNoticesJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryNewsNoticesById", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.QueryNewsNoticesById")
    @WebMethod
    @ResponseWrapper(localName = "queryNewsNoticesByIdResponse", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.QueryNewsNoticesByIdResponse")
    public java.lang.String queryNewsNoticesById(
        @WebParam(name = "newsNoticesJson", targetNamespace = "")
        java.lang.String newsNoticesJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryLinkExchangeById", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.QueryLinkExchangeById")
    @WebMethod
    @ResponseWrapper(localName = "queryLinkExchangeByIdResponse", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.QueryLinkExchangeByIdResponse")
    public java.lang.String queryLinkExchangeById(
        @WebParam(name = "linkJson", targetNamespace = "")
        java.lang.String linkJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "delNewsNotices", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.DelNewsNotices")
    @WebMethod
    @ResponseWrapper(localName = "delNewsNoticesResponse", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.DelNewsNoticesResponse")
    public java.lang.String delNewsNotices(
        @WebParam(name = "newsNoticesJson", targetNamespace = "")
        java.lang.String newsNoticesJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryNewsPptByPosition", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.QueryNewsPptByPosition")
    @WebMethod
    @ResponseWrapper(localName = "queryNewsPptByPositionResponse", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.QueryNewsPptByPositionResponse")
    public java.lang.String queryNewsPptByPosition(
        @WebParam(name = "params", targetNamespace = "")
        java.lang.String params
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryLinkExchangeListForFrontFriend", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.QueryLinkExchangeListForFrontFriend")
    @WebMethod
    @ResponseWrapper(localName = "queryLinkExchangeListForFrontFriendResponse", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.QueryLinkExchangeListForFrontFriendResponse")
    public java.lang.String queryLinkExchangeListForFrontFriend(
        @WebParam(name = "linkJson", targetNamespace = "")
        java.lang.String linkJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryLinkExchangeListForFrontPartner", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.QueryLinkExchangeListForFrontPartner")
    @WebMethod
    @ResponseWrapper(localName = "queryLinkExchangeListForFrontPartnerResponse", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.QueryLinkExchangeListForFrontPartnerResponse")
    public java.lang.String queryLinkExchangeListForFrontPartner(
        @WebParam(name = "linkJson", targetNamespace = "")
        java.lang.String linkJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryNewsNotices", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.QueryNewsNotices")
    @WebMethod
    @ResponseWrapper(localName = "queryNewsNoticesResponse", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.QueryNewsNoticesResponse")
    public java.lang.String queryNewsNotices(
        @WebParam(name = "newsNoticesJson", targetNamespace = "")
        java.lang.String newsNoticesJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryNewsPptListByFront", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.QueryNewsPptListByFront")
    @WebMethod
    @ResponseWrapper(localName = "queryNewsPptListByFrontResponse", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.QueryNewsPptListByFrontResponse")
    public java.lang.String queryNewsPptListByFront(
        @WebParam(name = "newsPptJson", targetNamespace = "")
        java.lang.String newsPptJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryLinkExchangeList", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.QueryLinkExchangeList")
    @WebMethod
    @ResponseWrapper(localName = "queryLinkExchangeListResponse", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.QueryLinkExchangeListResponse")
    public java.lang.String queryLinkExchangeList(
        @WebParam(name = "linkJson", targetNamespace = "")
        java.lang.String linkJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveLinkExchange", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.SaveLinkExchange")
    @WebMethod
    @ResponseWrapper(localName = "saveLinkExchangeResponse", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.SaveLinkExchangeResponse")
    public java.lang.String saveLinkExchange(
        @WebParam(name = "linkJson", targetNamespace = "")
        java.lang.String linkJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryNewsNoticesListForFront", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.QueryNewsNoticesListForFront")
    @WebMethod
    @ResponseWrapper(localName = "queryNewsNoticesListForFrontResponse", targetNamespace = "http://Interfaces.webService.news.xxdai.com/", className = "com.xxdai.news.webservice.interfaces.QueryNewsNoticesListForFrontResponse")
    public java.lang.String queryNewsNoticesListForFront(
        @WebParam(name = "newsNoticesJson", targetNamespace = "")
        java.lang.String newsNoticesJson
    );
}
