package com.xxdai.seo.ws.category;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2015-04-21T15:55:57.572+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://webservice.seo.xxdai.com/", name = "SeoCategoryCXFService")
@XmlSeeAlso({ObjectFactory.class})
public interface SeoCategoryCXFService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryAllTwoClass", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.QueryAllTwoClass")
    @WebMethod
    @ResponseWrapper(localName = "queryAllTwoClassResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.QueryAllTwoClassResponse")
    public java.lang.String queryAllTwoClass(
        @WebParam(name = "paramJson", targetNamespace = "")
        java.lang.String paramJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSeoInfoByCateID", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetSeoInfoByCateID")
    @WebMethod
    @ResponseWrapper(localName = "getSeoInfoByCateIDResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetSeoInfoByCateIDResponse")
    public java.lang.String getSeoInfoByCateID(
        @WebParam(name = "paramJson", targetNamespace = "")
        java.lang.String paramJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveSeoCategory", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.SaveSeoCategory")
    @WebMethod
    @ResponseWrapper(localName = "saveSeoCategoryResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.SaveSeoCategoryResponse")
    public java.lang.String saveSeoCategory(
        @WebParam(name = "seoCategoryJson", targetNamespace = "")
        java.lang.String seoCategoryJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryAllManagement", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.QueryAllManagement")
    @WebMethod
    @ResponseWrapper(localName = "queryAllManagementResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.QueryAllManagementResponse")
    public java.lang.String queryAllManagement(
        @WebParam(name = "paramJson", targetNamespace = "")
        java.lang.String paramJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryManagemenById", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.QueryManagemenById")
    @WebMethod
    @ResponseWrapper(localName = "queryManagemenByIdResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.QueryManagemenByIdResponse")
    public java.lang.String queryManagemenById(
        @WebParam(name = "mangementJson", targetNamespace = "")
        java.lang.String mangementJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCategoryByType", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetCategoryByType")
    @WebMethod
    @ResponseWrapper(localName = "getCategoryByTypeResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetCategoryByTypeResponse")
    public java.lang.String getCategoryByType(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryAllSeoSource", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.QueryAllSeoSource")
    @WebMethod
    @ResponseWrapper(localName = "queryAllSeoSourceResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.QueryAllSeoSourceResponse")
    public java.lang.String queryAllSeoSource(
        @WebParam(name = "paramJson", targetNamespace = "")
        java.lang.String paramJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getThirdPageHotFourth", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetThirdPageHotFourth")
    @WebMethod
    @ResponseWrapper(localName = "getThirdPageHotFourthResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetThirdPageHotFourthResponse")
    public java.lang.String getThirdPageHotFourth(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryAllThreeManagement", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.QueryAllThreeManagement")
    @WebMethod
    @ResponseWrapper(localName = "queryAllThreeManagementResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.QueryAllThreeManagementResponse")
    public java.lang.String queryAllThreeManagement(
        @WebParam(name = "paramJson", targetNamespace = "")
        java.lang.String paramJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryManagemenByCateID", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.QueryManagemenByCateID")
    @WebMethod
    @ResponseWrapper(localName = "queryManagemenByCateIDResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.QueryManagemenByCateIDResponse")
    public java.lang.String queryManagemenByCateID(
        @WebParam(name = "mangementJson", targetNamespace = "")
        java.lang.String mangementJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getThirdBySameOneNextTwo", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetThirdBySameOneNextTwo")
    @WebMethod
    @ResponseWrapper(localName = "getThirdBySameOneNextTwoResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetThirdBySameOneNextTwoResponse")
    public java.lang.String getThirdBySameOneNextTwo(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFourthPageHotFourth", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetFourthPageHotFourth")
    @WebMethod
    @ResponseWrapper(localName = "getFourthPageHotFourthResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetFourthPageHotFourthResponse")
    public java.lang.String getFourthPageHotFourth(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryOneClassManagement", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.QueryOneClassManagement")
    @WebMethod
    @ResponseWrapper(localName = "queryOneClassManagementResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.QueryOneClassManagementResponse")
    public java.lang.String queryOneClassManagement(
        @WebParam(name = "programManagementJson", targetNamespace = "")
        java.lang.String programManagementJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFistXgzt", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetFistXgzt")
    @WebMethod
    @ResponseWrapper(localName = "getFistXgztResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetFistXgztResponse")
    public java.lang.String getFistXgzt(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFourCategoryByHot", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetFourCategoryByHot")
    @WebMethod
    @ResponseWrapper(localName = "getFourCategoryByHotResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetFourCategoryByHotResponse")
    public java.lang.String getFourCategoryByHot(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFourNewInfo", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetFourNewInfo")
    @WebMethod
    @ResponseWrapper(localName = "getFourNewInfoResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetFourNewInfoResponse")
    public java.lang.String getFourNewInfo();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSeoCategoryById", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetSeoCategoryById")
    @WebMethod
    @ResponseWrapper(localName = "getSeoCategoryByIdResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetSeoCategoryByIdResponse")
    public java.lang.String getSeoCategoryById(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCategoryByParentId", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetCategoryByParentId")
    @WebMethod
    @ResponseWrapper(localName = "getCategoryByParentIdResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetCategoryByParentIdResponse")
    public java.lang.String getCategoryByParentId(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryListOneClass", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.QueryListOneClass")
    @WebMethod
    @ResponseWrapper(localName = "queryListOneClassResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.QueryListOneClassResponse")
    public java.lang.String queryListOneClass(
        @WebParam(name = "paramsjson", targetNamespace = "")
        java.lang.String paramsjson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCategoryByBaidu", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetCategoryByBaidu")
    @WebMethod
    @ResponseWrapper(localName = "getCategoryByBaiduResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetCategoryByBaiduResponse")
    public java.lang.String getCategoryByBaidu(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getThridSeoCategoryByFirstCate", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetThridSeoCategoryByFirstCate")
    @WebMethod
    @ResponseWrapper(localName = "getThridSeoCategoryByFirstCateResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetThridSeoCategoryByFirstCateResponse")
    public java.lang.String getThridSeoCategoryByFirstCate(
        @WebParam(name = "paramJson", targetNamespace = "")
        java.lang.String paramJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFourCategoryBySecHot", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetFourCategoryBySecHot")
    @WebMethod
    @ResponseWrapper(localName = "getFourCategoryBySecHotResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetFourCategoryBySecHotResponse")
    public java.lang.String getFourCategoryBySecHot(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryOneClassById", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.QueryOneClassById")
    @WebMethod
    @ResponseWrapper(localName = "queryOneClassByIdResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.QueryOneClassByIdResponse")
    public java.lang.String queryOneClassById(
        @WebParam(name = "seoCategoryJson", targetNamespace = "")
        java.lang.String seoCategoryJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getThridCategoryByHot", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetThridCategoryByHot")
    @WebMethod
    @ResponseWrapper(localName = "getThridCategoryByHotResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.GetThridCategoryByHotResponse")
    public java.lang.String getThridCategoryByHot(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryOneClassByCateName", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.QueryOneClassByCateName")
    @WebMethod
    @ResponseWrapper(localName = "queryOneClassByCateNameResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.category.QueryOneClassByCateNameResponse")
    public java.lang.String queryOneClassByCateName(
        @WebParam(name = "seoCategoryJson", targetNamespace = "")
        java.lang.String seoCategoryJson
    );
}
