package com.xxdai.person.ws.accountov;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-17T18:19:26.309+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://interfaces.webService.xxdai.com/", name = "AccountOVQueryCXFService")
@XmlSeeAlso({ObjectFactory.class})
public interface AccountOVQueryCXFService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryVIPByUserId", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.accountov.QueryVIPByUserId")
    @WebMethod
    @ResponseWrapper(localName = "queryVIPByUserIdResponse", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.accountov.QueryVIPByUserIdResponse")
    public java.lang.String queryVIPByUserId(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryMobileByUserId", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.accountov.QueryMobileByUserId")
    @WebMethod
    @ResponseWrapper(localName = "queryMobileByUserIdResponse", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.accountov.QueryMobileByUserIdResponse")
    public java.lang.String queryMobileByUserId(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryRealNameByUserId", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.accountov.QueryRealNameByUserId")
    @WebMethod
    @ResponseWrapper(localName = "queryRealNameByUserIdResponse", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.accountov.QueryRealNameByUserIdResponse")
    public java.lang.String queryRealNameByUserId(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryEmailByUserId", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.accountov.QueryEmailByUserId")
    @WebMethod
    @ResponseWrapper(localName = "queryEmailByUserIdResponse", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.accountov.QueryEmailByUserIdResponse")
    public java.lang.String queryEmailByUserId(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId
    );
}
