package com.xxdai.person.ws.accountov;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-17T18:19:26.356+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebServiceClient(name = "AccountOVQueryCXFServiceImplService", 
                  wsdlLocation = "http://localhost:8080/v6_webservice/service/accountOVQueryWebService?wsdl",
                  targetNamespace = "http://impl.webService.xxdai.com/") 
public class AccountOVQueryCXFServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webService.xxdai.com/", "AccountOVQueryCXFServiceImplService");
    public final static QName AccountOVQueryCXFServiceImplPort = new QName("http://impl.webService.xxdai.com/", "AccountOVQueryCXFServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/v6_webservice/service/accountOVQueryWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AccountOVQueryCXFServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/v6_webservice/service/accountOVQueryWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AccountOVQueryCXFServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AccountOVQueryCXFServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountOVQueryCXFServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AccountOVQueryCXFService
     */
    @WebEndpoint(name = "AccountOVQueryCXFServiceImplPort")
    public AccountOVQueryCXFService getAccountOVQueryCXFServiceImplPort() {
        return super.getPort(AccountOVQueryCXFServiceImplPort, AccountOVQueryCXFService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountOVQueryCXFService
     */
    @WebEndpoint(name = "AccountOVQueryCXFServiceImplPort")
    public AccountOVQueryCXFService getAccountOVQueryCXFServiceImplPort(WebServiceFeature... features) {
        return super.getPort(AccountOVQueryCXFServiceImplPort, AccountOVQueryCXFService.class, features);
    }

}
