package com.xxdai.person.ws.appro;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-05T16:29:32.218+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://webService.appro.xxdai.com/", name = "ApproCXFService")
@XmlSeeAlso({ObjectFactory.class})
public interface ApproCXFService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkMobileIsExisting", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.appro.CheckMobileIsExisting")
    @WebMethod
    @ResponseWrapper(localName = "checkMobileIsExistingResponse", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.appro.CheckMobileIsExistingResponse")
    public java.lang.String checkMobileIsExisting(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkEmailMsg", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.appro.CheckEmailMsg")
    @WebMethod
    @ResponseWrapper(localName = "checkEmailMsgResponse", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.appro.CheckEmailMsgResponse")
    public java.lang.String checkEmailMsg(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "auditVip", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.appro.AuditVip")
    @WebMethod
    @ResponseWrapper(localName = "auditVipResponse", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.appro.AuditVipResponse")
    public java.lang.String auditVip(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkVip", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.appro.CheckVip")
    @WebMethod
    @ResponseWrapper(localName = "checkVipResponse", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.appro.CheckVipResponse")
    public java.lang.String checkVip(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendSmsMsg", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.appro.SendSmsMsg")
    @WebMethod
    @ResponseWrapper(localName = "sendSmsMsgResponse", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.appro.SendSmsMsgResponse")
    public java.lang.String sendSmsMsg(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkRealName", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.appro.CheckRealName")
    @WebMethod
    @ResponseWrapper(localName = "checkRealNameResponse", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.appro.CheckRealNameResponse")
    public java.lang.String checkRealName(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkSmsMsg", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.appro.CheckSmsMsg")
    @WebMethod
    @ResponseWrapper(localName = "checkSmsMsgResponse", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.appro.CheckSmsMsgResponse")
    public java.lang.String checkSmsMsg(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "auditRealName", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.appro.AuditRealName")
    @WebMethod
    @ResponseWrapper(localName = "auditRealNameResponse", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.appro.AuditRealNameResponse")
    public java.lang.String auditRealName(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendEmailMsg", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.appro.SendEmailMsg")
    @WebMethod
    @ResponseWrapper(localName = "sendEmailMsgResponse", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.appro.SendEmailMsgResponse")
    public java.lang.String sendEmailMsg(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendSmsMsgFromReg", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.appro.SendSmsMsgFromReg")
    @WebMethod
    @ResponseWrapper(localName = "sendSmsMsgFromRegResponse", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.appro.SendSmsMsgFromRegResponse")
    public java.lang.String sendSmsMsgFromReg(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );
}
