
package com.xxdai.person.ws.appro;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-05T16:29:32.162+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class ApproCXFService_ApproCXFServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.webService.appro.xxdai.com/", "ApproCXFServiceImplService");

    private ApproCXFService_ApproCXFServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ApproCXFServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ApproCXFServiceImplService ss = new ApproCXFServiceImplService(wsdlURL, SERVICE_NAME);
        ApproCXFService port = ss.getApproCXFServiceImplPort();  
        
        {
        System.out.println("Invoking checkMobileIsExisting...");
        java.lang.String _checkMobileIsExisting_jsonstring = "";
        java.lang.String _checkMobileIsExisting__return = port.checkMobileIsExisting(_checkMobileIsExisting_jsonstring);
        System.out.println("checkMobileIsExisting.result=" + _checkMobileIsExisting__return);


        }
        {
        System.out.println("Invoking checkEmailMsg...");
        java.lang.String _checkEmailMsg_jsonstring = "";
        java.lang.String _checkEmailMsg__return = port.checkEmailMsg(_checkEmailMsg_jsonstring);
        System.out.println("checkEmailMsg.result=" + _checkEmailMsg__return);


        }
        {
        System.out.println("Invoking auditVip...");
        java.lang.String _auditVip_jsonstring = "";
        java.lang.String _auditVip__return = port.auditVip(_auditVip_jsonstring);
        System.out.println("auditVip.result=" + _auditVip__return);


        }
        {
        System.out.println("Invoking checkVip...");
        java.lang.String _checkVip_jsonstring = "";
        java.lang.String _checkVip__return = port.checkVip(_checkVip_jsonstring);
        System.out.println("checkVip.result=" + _checkVip__return);


        }
        {
        System.out.println("Invoking sendSmsMsg...");
        java.lang.String _sendSmsMsg_jsonstring = "";
        java.lang.String _sendSmsMsg__return = port.sendSmsMsg(_sendSmsMsg_jsonstring);
        System.out.println("sendSmsMsg.result=" + _sendSmsMsg__return);


        }
        {
        System.out.println("Invoking checkRealName...");
        java.lang.String _checkRealName_jsonstring = "";
        java.lang.String _checkRealName__return = port.checkRealName(_checkRealName_jsonstring);
        System.out.println("checkRealName.result=" + _checkRealName__return);


        }
        {
        System.out.println("Invoking checkSmsMsg...");
        java.lang.String _checkSmsMsg_jsonstring = "";
        java.lang.String _checkSmsMsg__return = port.checkSmsMsg(_checkSmsMsg_jsonstring);
        System.out.println("checkSmsMsg.result=" + _checkSmsMsg__return);


        }
        {
        System.out.println("Invoking auditRealName...");
        java.lang.String _auditRealName_jsonstring = "";
        java.lang.String _auditRealName__return = port.auditRealName(_auditRealName_jsonstring);
        System.out.println("auditRealName.result=" + _auditRealName__return);


        }
        {
        System.out.println("Invoking sendEmailMsg...");
        java.lang.String _sendEmailMsg_jsonstring = "";
        java.lang.String _sendEmailMsg__return = port.sendEmailMsg(_sendEmailMsg_jsonstring);
        System.out.println("sendEmailMsg.result=" + _sendEmailMsg__return);


        }
        {
        System.out.println("Invoking sendSmsMsgFromReg...");
        java.lang.String _sendSmsMsgFromReg_jsonstring = "";
        java.lang.String _sendSmsMsgFromReg__return = port.sendSmsMsgFromReg(_sendSmsMsgFromReg_jsonstring);
        System.out.println("sendSmsMsgFromReg.result=" + _sendSmsMsgFromReg__return);


        }

        System.exit(0);
    }

}
