package com.xxdai.person.ws.approquery;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-05T16:30:07.211+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebServiceClient(name = "ApproQueryCXFServiceImplService", 
                  wsdlLocation = "http://localhost:8080/v6_webservice/service/approQueryWebService?wsdl",
                  targetNamespace = "http://impl.webService.appro.xxdai.com/") 
public class ApproQueryCXFServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webService.appro.xxdai.com/", "ApproQueryCXFServiceImplService");
    public final static QName ApproQueryCXFServiceImplPort = new QName("http://impl.webService.appro.xxdai.com/", "ApproQueryCXFServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/v6_webservice/service/approQueryWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ApproQueryCXFServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/v6_webservice/service/approQueryWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ApproQueryCXFServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ApproQueryCXFServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApproQueryCXFServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ApproQueryCXFService
     */
    @WebEndpoint(name = "ApproQueryCXFServiceImplPort")
    public ApproQueryCXFService getApproQueryCXFServiceImplPort() {
        return super.getPort(ApproQueryCXFServiceImplPort, ApproQueryCXFService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ApproQueryCXFService
     */
    @WebEndpoint(name = "ApproQueryCXFServiceImplPort")
    public ApproQueryCXFService getApproQueryCXFServiceImplPort(WebServiceFeature... features) {
        return super.getPort(ApproQueryCXFServiceImplPort, ApproQueryCXFService.class, features);
    }

}
