package com.xxdai.person.ws.approquery;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-05T16:30:07.165+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://webService.appro.xxdai.com/", name = "ApproQueryCXFService")
@XmlSeeAlso({ObjectFactory.class})
public interface ApproQueryCXFService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryVipApproEmployeeNum", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.approquery.QueryVipApproEmployeeNum")
    @WebMethod
    @ResponseWrapper(localName = "queryVipApproEmployeeNumResponse", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.approquery.QueryVipApproEmployeeNumResponse")
    public java.lang.String queryVipApproEmployeeNum(
        @WebParam(name = "jobNum", targetNamespace = "")
        java.lang.String jobNum
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryEmailApproByUserId", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.approquery.QueryEmailApproByUserId")
    @WebMethod
    @ResponseWrapper(localName = "queryEmailApproByUserIdResponse", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.approquery.QueryEmailApproByUserIdResponse")
    public java.lang.String queryEmailApproByUserId(
        @WebParam(name = "userIdJson", targetNamespace = "")
        java.lang.String userIdJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryRealNameApproByUserId", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.approquery.QueryRealNameApproByUserId")
    @WebMethod
    @ResponseWrapper(localName = "queryRealNameApproByUserIdResponse", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.approquery.QueryRealNameApproByUserIdResponse")
    public java.lang.String queryRealNameApproByUserId(
        @WebParam(name = "userJson", targetNamespace = "")
        java.lang.String userJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryVipApproEmployee", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.approquery.QueryVipApproEmployee")
    @WebMethod
    @ResponseWrapper(localName = "queryVipApproEmployeeResponse", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.approquery.QueryVipApproEmployeeResponse")
    public java.lang.String queryVipApproEmployee();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryMobileApproByUserId", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.approquery.QueryMobileApproByUserId")
    @WebMethod
    @ResponseWrapper(localName = "queryMobileApproByUserIdResponse", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.approquery.QueryMobileApproByUserIdResponse")
    public java.lang.String queryMobileApproByUserId(
        @WebParam(name = "userIdJson", targetNamespace = "")
        java.lang.String userIdJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryMobileApproByPhotoNum", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.approquery.QueryMobileApproByPhotoNum")
    @WebMethod
    @ResponseWrapper(localName = "queryMobileApproByPhotoNumResponse", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.approquery.QueryMobileApproByPhotoNumResponse")
    public java.lang.String queryMobileApproByPhotoNum(
        @WebParam(name = "numJson", targetNamespace = "")
        java.lang.String numJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryRealNameApproById", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.approquery.QueryRealNameApproById")
    @WebMethod
    @ResponseWrapper(localName = "queryRealNameApproByIdResponse", targetNamespace = "http://webService.appro.xxdai.com/", className = "com.xxdai.person.ws.approquery.QueryRealNameApproByIdResponse")
    public java.lang.String queryRealNameApproById(
        @WebParam(name = "idJson", targetNamespace = "")
        java.lang.String idJson
    );
}
