
package com.xxdai.person.ws.accountCashprohibit;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2016-09-27T10:17:43.402+08:00
 * Generated source version: 2.7.12
 * 
 */
public final class AccountCashprohibitCXFService_AccountCashprohibitCXFServiceImpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.webService.xxdai.com/", "AccountCashprohibitCXFServiceImpService");

    private AccountCashprohibitCXFService_AccountCashprohibitCXFServiceImpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AccountCashprohibitCXFServiceImpService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AccountCashprohibitCXFServiceImpService ss = new AccountCashprohibitCXFServiceImpService(wsdlURL, SERVICE_NAME);
        AccountCashprohibitCXFService port = ss.getAccountCashprohibitCXFServiceImpPort();  
        
        {
        System.out.println("Invoking selectByUserIdIsFS...");
        java.lang.String _selectByUserIdIsFS_jsonStr = "";
        java.lang.String _selectByUserIdIsFS__return = port.selectByUserIdIsFS(_selectByUserIdIsFS_jsonStr);
        System.out.println("selectByUserIdIsFS.result=" + _selectByUserIdIsFS__return);


        }

        System.exit(0);
    }

}
