
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.xxdai.person.ws.accountCashprohibit;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2016-09-27T10:17:43.422+08:00
 * Generated source version: 2.7.12
 * 
 */

@javax.jws.WebService(
                      serviceName = "AccountCashprohibitCXFServiceImpService",
                      portName = "AccountCashprohibitCXFServiceImpPort",
                      targetNamespace = "http://impl.webService.xxdai.com/",
                      wsdlLocation = "http://test.xxd.com/v6_webservice/service/accountCashprohibitWebService?wsdl",
                      endpointInterface = "com.xxdai.person.ws.accountCashprohibit.AccountCashprohibitCXFService")
                      
public class AccountCashprohibitCXFServiceImpl implements AccountCashprohibitCXFService {

    private static final Logger LOG = Logger.getLogger(AccountCashprohibitCXFServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.xxdai.person.ws.accountCashprohibit.AccountCashprohibitCXFService#selectByUserIdIsFS(java.lang.String  jsonStr )*
     */
    public java.lang.String selectByUserIdIsFS(java.lang.String jsonStr) { 
        LOG.info("Executing operation selectByUserIdIsFS");
        System.out.println(jsonStr);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
