
package com.xxdai.person.ws.accountCashprohibit;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2016-09-27T10:17:43.437+08:00
 * Generated source version: 2.7.12
 * 
 */
 
public class AccountCashprohibitCXFService_AccountCashprohibitCXFServiceImpPort_Server{

    protected AccountCashprohibitCXFService_AccountCashprohibitCXFServiceImpPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new AccountCashprohibitCXFServiceImpl();
        String address = "http://test.xxd.com/v6_webservice/service/accountCashprohibitWebService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new AccountCashprohibitCXFService_AccountCashprohibitCXFServiceImpPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
