package com.xxdai.person.ws.baseinfo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-08-28T15:35:21.954+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebServiceClient(name = "BaseInfoCXFServiceImplService", 
                  wsdlLocation = "http://localhost:8080/v6_front/service/baseInfoWebService?wsdl",
                  targetNamespace = "http://impl.webService.xxdai.com/") 
public class BaseInfoCXFServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webService.xxdai.com/", "BaseInfoCXFServiceImplService");
    public final static QName BaseInfoCXFServiceImplPort = new QName("http://impl.webService.xxdai.com/", "BaseInfoCXFServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/v6_front/service/baseInfoWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BaseInfoCXFServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/v6_front/service/baseInfoWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BaseInfoCXFServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BaseInfoCXFServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BaseInfoCXFServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns BaseInfoCXFService
     */
    @WebEndpoint(name = "BaseInfoCXFServiceImplPort")
    public BaseInfoCXFService getBaseInfoCXFServiceImplPort() {
        return super.getPort(BaseInfoCXFServiceImplPort, BaseInfoCXFService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BaseInfoCXFService
     */
    @WebEndpoint(name = "BaseInfoCXFServiceImplPort")
    public BaseInfoCXFService getBaseInfoCXFServiceImplPort(WebServiceFeature... features) {
        return super.getPort(BaseInfoCXFServiceImplPort, BaseInfoCXFService.class, features);
    }

}
