package com.xxdai.person.ws.baseinfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-08-28T15:35:21.923+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://interfaces.webService.xxdai.com/", name = "BaseInfoCXFService")
@XmlSeeAlso({ObjectFactory.class})
public interface BaseInfoCXFService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "alterBaseInfo", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.baseinfo.AlterBaseInfo")
    @WebMethod
    @ResponseWrapper(localName = "alterBaseInfoResponse", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.baseinfo.AlterBaseInfoResponse")
    public java.lang.String alterBaseInfo(
        @WebParam(name = "alterBaseInfoJson", targetNamespace = "")
        java.lang.String alterBaseInfoJson
    );
}
