package com.xxdai.person.ws.pwoperate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-02T14:21:44.867+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://interfaces.webService.xxdai.com/", name = "PwOperateCXFService")
@XmlSeeAlso({ObjectFactory.class})
public interface PwOperateCXFService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateUserPwdPro", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.pwoperate.UpdateUserPwdPro")
    @WebMethod
    @ResponseWrapper(localName = "updateUserPwdProResponse", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.pwoperate.UpdateUserPwdProResponse")
    public java.lang.String updateUserPwdPro(
        @WebParam(name = "secJson", targetNamespace = "")
        java.lang.String secJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updatePW", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.pwoperate.UpdatePW")
    @WebMethod
    @ResponseWrapper(localName = "updatePWResponse", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.pwoperate.UpdatePWResponse")
    public java.lang.String updatePW(
        @WebParam(name = "namePWTypeJson", targetNamespace = "")
        java.lang.String namePWTypeJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryUser", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.pwoperate.QueryUser")
    @WebMethod
    @ResponseWrapper(localName = "queryUserResponse", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.pwoperate.QueryUserResponse")
    public java.lang.String queryUser(
        @WebParam(name = "userNameJson", targetNamespace = "")
        java.lang.String userNameJson
    );
}
