package com.xxdai.person.ws.pwoperate;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-02T14:21:44.899+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebServiceClient(name = "PwOperateCXFServiceImplService", 
                  wsdlLocation = "http://localhost:8080/v6_webservice/service/pwoperateWebService?wsdl",
                  targetNamespace = "http://impl.webService.xxdai.com/") 
public class PwOperateCXFServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webService.xxdai.com/", "PwOperateCXFServiceImplService");
    public final static QName PwOperateCXFServiceImplPort = new QName("http://impl.webService.xxdai.com/", "PwOperateCXFServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/v6_webservice/service/pwoperateWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PwOperateCXFServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/v6_webservice/service/pwoperateWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PwOperateCXFServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PwOperateCXFServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PwOperateCXFServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns PwOperateCXFService
     */
    @WebEndpoint(name = "PwOperateCXFServiceImplPort")
    public PwOperateCXFService getPwOperateCXFServiceImplPort() {
        return super.getPort(PwOperateCXFServiceImplPort, PwOperateCXFService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PwOperateCXFService
     */
    @WebEndpoint(name = "PwOperateCXFServiceImplPort")
    public PwOperateCXFService getPwOperateCXFServiceImplPort(WebServiceFeature... features) {
        return super.getPort(PwOperateCXFServiceImplPort, PwOperateCXFService.class, features);
    }

}
