package com.xxdai.seo.ws.link;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2015-01-09T10:58:22.576+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebServiceClient(name = "SeoLinkExchangeCXFServiceImplService", 
                  wsdlLocation = "http://localhost:8080/v6_webservice/service/seoLinkExchangeCXFService?wsdl",
                  targetNamespace = "http://impl.webservice.seo.xxdai.com/") 
public class SeoLinkExchangeCXFServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.seo.xxdai.com/", "SeoLinkExchangeCXFServiceImplService");
    public final static QName SeoLinkExchangeCXFServiceImplPort = new QName("http://impl.webservice.seo.xxdai.com/", "SeoLinkExchangeCXFServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/v6_webservice/service/seoLinkExchangeCXFService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SeoLinkExchangeCXFServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/v6_webservice/service/seoLinkExchangeCXFService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SeoLinkExchangeCXFServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SeoLinkExchangeCXFServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SeoLinkExchangeCXFServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SeoLinkExchangeCXFService
     */
    @WebEndpoint(name = "SeoLinkExchangeCXFServiceImplPort")
    public SeoLinkExchangeCXFService getSeoLinkExchangeCXFServiceImplPort() {
        return super.getPort(SeoLinkExchangeCXFServiceImplPort, SeoLinkExchangeCXFService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SeoLinkExchangeCXFService
     */
    @WebEndpoint(name = "SeoLinkExchangeCXFServiceImplPort")
    public SeoLinkExchangeCXFService getSeoLinkExchangeCXFServiceImplPort(WebServiceFeature... features) {
        return super.getPort(SeoLinkExchangeCXFServiceImplPort, SeoLinkExchangeCXFService.class, features);
    }

}
