package com.xxdai.seo.ws.link;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2015-01-09T10:58:22.545+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://webservice.seo.xxdai.com/", name = "SeoLinkExchangeCXFService")
@XmlSeeAlso({ObjectFactory.class})
public interface SeoLinkExchangeCXFService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLinkExchangeById", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.link.GetLinkExchangeById")
    @WebMethod
    @ResponseWrapper(localName = "getLinkExchangeByIdResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.link.GetLinkExchangeByIdResponse")
    public java.lang.String getLinkExchangeById(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteLinkById", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.link.DeleteLinkById")
    @WebMethod
    @ResponseWrapper(localName = "deleteLinkByIdResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.link.DeleteLinkByIdResponse")
    public java.lang.String deleteLinkById(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLinkExchangeList", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.link.GetLinkExchangeList")
    @WebMethod
    @ResponseWrapper(localName = "getLinkExchangeListResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.link.GetLinkExchangeListResponse")
    public java.lang.String getLinkExchangeList(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveOrUpdateLink", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.link.SaveOrUpdateLink")
    @WebMethod
    @ResponseWrapper(localName = "saveOrUpdateLinkResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.link.SaveOrUpdateLinkResponse")
    public java.lang.String saveOrUpdateLink(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getlinkListByCateType", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.link.GetlinkListByCateType")
    @WebMethod
    @ResponseWrapper(localName = "getlinkListByCateTypeResponse", targetNamespace = "http://webservice.seo.xxdai.com/", className = "com.xxdai.seo.ws.link.GetlinkListByCateTypeResponse")
    public java.lang.String getlinkListByCateType(
        @WebParam(name = "jsonstring", targetNamespace = "")
        java.lang.String jsonstring
    );
}
