package com.xxdai.person.ws.userquery;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-11-14T11:38:40.342+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebServiceClient(name = "UserQueryCXFServiceImplService", 
                  wsdlLocation = "http://localhost:8080/v6_webservice/service/userQueryWebService?wsdl",
                  targetNamespace = "http://impl.webService.xxdai.com/") 
public class UserQueryCXFServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webService.xxdai.com/", "UserQueryCXFServiceImplService");
    public final static QName UserQueryCXFServiceImplPort = new QName("http://impl.webService.xxdai.com/", "UserQueryCXFServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/v6_webservice/service/userQueryWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserQueryCXFServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/v6_webservice/service/userQueryWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserQueryCXFServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserQueryCXFServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserQueryCXFServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns UserQueryCXFService
     */
    @WebEndpoint(name = "UserQueryCXFServiceImplPort")
    public UserQueryCXFService getUserQueryCXFServiceImplPort() {
        return super.getPort(UserQueryCXFServiceImplPort, UserQueryCXFService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserQueryCXFService
     */
    @WebEndpoint(name = "UserQueryCXFServiceImplPort")
    public UserQueryCXFService getUserQueryCXFServiceImplPort(WebServiceFeature... features) {
        return super.getPort(UserQueryCXFServiceImplPort, UserQueryCXFService.class, features);
    }

}
