package com.xxdai.person.ws.userquery;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-11-14T11:38:40.170+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://interfaces.webService.xxdai.com/", name = "UserQueryCXFService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserQueryCXFService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryById", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.userquery.QueryById")
    @WebMethod
    @ResponseWrapper(localName = "queryByIdResponse", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.userquery.QueryByIdResponse")
    public java.lang.String queryById(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryByUserIdOrpwValue", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.userquery.QueryByUserIdOrpwValue")
    @WebMethod
    @ResponseWrapper(localName = "queryByUserIdOrpwValueResponse", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.userquery.QueryByUserIdOrpwValueResponse")
    public java.lang.String queryByUserIdOrpwValue(
        @WebParam(name = "parmstr", targetNamespace = "")
        java.lang.String parmstr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryUserByName", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.userquery.QueryUserByName")
    @WebMethod
    @ResponseWrapper(localName = "queryUserByNameResponse", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.userquery.QueryUserByNameResponse")
    public java.lang.String queryUserByName(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectUserByEmail", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.userquery.SelectUserByEmail")
    @WebMethod
    @ResponseWrapper(localName = "selectUserByEmailResponse", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.userquery.SelectUserByEmailResponse")
    public java.lang.String selectUserByEmail(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryBaseInfo", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.userquery.QueryBaseInfo")
    @WebMethod
    @ResponseWrapper(localName = "queryBaseInfoResponse", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.userquery.QueryBaseInfoResponse")
    public java.lang.String queryBaseInfo(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateUserHeadImg", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.userquery.UpdateUserHeadImg")
    @WebMethod
    @ResponseWrapper(localName = "updateUserHeadImgResponse", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.userquery.UpdateUserHeadImgResponse")
    public java.lang.String updateUserHeadImg(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectUserByMobile", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.userquery.SelectUserByMobile")
    @WebMethod
    @ResponseWrapper(localName = "selectUserByMobileResponse", targetNamespace = "http://interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.userquery.SelectUserByMobileResponse")
    public java.lang.String selectUserByMobile(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username
    );
}
