package com.xxdai.person.ws.user;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-04T15:45:57.466+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://user.interfaces.webService.xxdai.com/", name = "UserCXFService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserCXFService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "regist", targetNamespace = "http://user.interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.user.Regist")
    @WebMethod
    @ResponseWrapper(localName = "registResponse", targetNamespace = "http://user.interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.user.RegistResponse")
    public com.xxdai.person.ws.user.User regist(
        @WebParam(name = "user", targetNamespace = "")
        com.xxdai.person.ws.user.User user,
        @WebParam(name = "ip", targetNamespace = "")
        java.lang.String ip,
        @WebParam(name = "linkage", targetNamespace = "")
        java.lang.String linkage
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "uniqueUserName", targetNamespace = "http://user.interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.user.UniqueUserName")
    @WebMethod
    @ResponseWrapper(localName = "uniqueUserNameResponse", targetNamespace = "http://user.interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.user.UniqueUserNameResponse")
    public int uniqueUserName(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://user.interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.user.Login")
    @WebMethod
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://user.interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.user.LoginResponse")
    public java.lang.String login(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "lastIp", targetNamespace = "")
        java.lang.String lastIp
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "uniqueEmail", targetNamespace = "http://user.interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.user.UniqueEmail")
    @WebMethod
    @ResponseWrapper(localName = "uniqueEmailResponse", targetNamespace = "http://user.interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.user.UniqueEmailResponse")
    public int uniqueEmail(
        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registMobile", targetNamespace = "http://user.interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.user.RegistMobile")
    @WebMethod
    @ResponseWrapper(localName = "registMobileResponse", targetNamespace = "http://user.interfaces.webService.xxdai.com/", className = "com.xxdai.person.ws.user.RegistMobileResponse")
    public int registMobile(
        @WebParam(name = "user", targetNamespace = "")
        com.xxdai.person.ws.user.User user,
        @WebParam(name = "ip", targetNamespace = "")
        java.lang.String ip,
        @WebParam(name = "linkage", targetNamespace = "")
        java.lang.String linkage,
        @WebParam(name = "mobileNum", targetNamespace = "")
        java.lang.String mobileNum,
        @WebParam(name = "mobileCode", targetNamespace = "")
        java.lang.String mobileCode
    );
}
