package com.xxdai.person.ws.user;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-04T15:45:57.497+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebServiceClient(name = "UserCXFServiceImpService", 
                  wsdlLocation = "http://localhost:8080/v6_webservice/service/userWebService?wsdl",
                  targetNamespace = "http://user.impl.webService.xxdai.com/") 
public class UserCXFServiceImpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://user.impl.webService.xxdai.com/", "UserCXFServiceImpService");
    public final static QName UserCXFServiceImpPort = new QName("http://user.impl.webService.xxdai.com/", "UserCXFServiceImpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/v6_webservice/service/userWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserCXFServiceImpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/v6_webservice/service/userWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserCXFServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserCXFServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserCXFServiceImpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns UserCXFService
     */
    @WebEndpoint(name = "UserCXFServiceImpPort")
    public UserCXFService getUserCXFServiceImpPort() {
        return super.getPort(UserCXFServiceImpPort, UserCXFService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserCXFService
     */
    @WebEndpoint(name = "UserCXFServiceImpPort")
    public UserCXFService getUserCXFServiceImpPort(WebServiceFeature... features) {
        return super.getPort(UserCXFServiceImpPort, UserCXFService.class, features);
    }

}
