package com.xxdai.system.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-11-20T18:49:22.601+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://webservice.system.xxdai.com/", name = "AreaQueryCXFService")
@XmlSeeAlso({ObjectFactory.class})
public interface AreaQueryCXFService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryLowerArea", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.QueryLowerArea")
    @WebMethod
    @ResponseWrapper(localName = "queryLowerAreaResponse", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.QueryLowerAreaResponse")
    public java.lang.String queryLowerArea(
        @WebParam(name = "area", targetNamespace = "")
        java.lang.String area
    );
}
