package com.xxdai.system.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-10-15T18:24:23.444+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://webservice.system.xxdai.com/", name = "DicCXFService")
@XmlSeeAlso({ObjectFactory.class})
public interface DicCXFService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryPageDicCommon", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.QueryPageDicCommon")
    @WebMethod
    @ResponseWrapper(localName = "queryPageDicCommonResponse", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.QueryPageDicCommonResponse")
    public java.lang.String queryPageDicCommon(
        @WebParam(name = "queryParam", targetNamespace = "")
        java.lang.String queryParam
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateDicCommon", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.UpdateDicCommon")
    @WebMethod
    @ResponseWrapper(localName = "updateDicCommonResponse", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.UpdateDicCommonResponse")
    public java.lang.String updateDicCommon(
        @WebParam(name = "updateParam", targetNamespace = "")
        java.lang.String updateParam
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryCommonValue", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.QueryCommonValue")
    @WebMethod
    @ResponseWrapper(localName = "queryCommonValueResponse", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.QueryCommonValueResponse")
    public java.lang.String queryCommonValue(
        @WebParam(name = "code", targetNamespace = "")
        java.lang.String code
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryPageDic", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.QueryPageDic")
    @WebMethod
    @ResponseWrapper(localName = "queryPageDicResponse", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.QueryPageDicResponse")
    public java.lang.String queryPageDic(
        @WebParam(name = "updateParam", targetNamespace = "")
        java.lang.String updateParam
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateDic", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.UpdateDic")
    @WebMethod
    @ResponseWrapper(localName = "updateDicResponse", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.UpdateDicResponse")
    public java.lang.String updateDic(
        @WebParam(name = "updateParam", targetNamespace = "")
        java.lang.String updateParam
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryObjectById", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.QueryObjectById")
    @WebMethod
    @ResponseWrapper(localName = "queryObjectByIdResponse", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.QueryObjectByIdResponse")
    public java.lang.String queryObjectById(
        @WebParam(name = "queryId", targetNamespace = "")
        java.lang.String queryId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addDic", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.AddDic")
    @WebMethod
    @ResponseWrapper(localName = "addDicResponse", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.AddDicResponse")
    public java.lang.String addDic(
        @WebParam(name = "addParam", targetNamespace = "")
        java.lang.String addParam
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryAllTypeCode", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.QueryAllTypeCode")
    @WebMethod
    @ResponseWrapper(localName = "queryAllTypeCodeResponse", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.QueryAllTypeCodeResponse")
    public java.lang.String queryAllTypeCode();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryDicCommonByTypeCodeAndPkey", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.QueryDicCommonByTypeCodeAndPkey")
    @WebMethod
    @ResponseWrapper(localName = "queryDicCommonByTypeCodeAndPkeyResponse", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.QueryDicCommonByTypeCodeAndPkeyResponse")
    public java.lang.String queryDicCommonByTypeCodeAndPkey(
        @WebParam(name = "queryParam", targetNamespace = "")
        java.lang.String queryParam
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addDicCommon", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.AddDicCommon")
    @WebMethod
    @ResponseWrapper(localName = "addDicCommonResponse", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.AddDicCommonResponse")
    public java.lang.String addDicCommon(
        @WebParam(name = "addParam", targetNamespace = "")
        java.lang.String addParam
    );
}
