
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.xxdai.system.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2016-10-17T11:40:36.912+08:00
 * Generated source version: 2.7.12
 * 
 */

@javax.jws.WebService(
                      serviceName = "SysConfigCXFServiceImplService",
                      portName = "SysConfigCXFServiceImplPort",
                      targetNamespace = "http://impl.webservice.system.xxdai.com/",
                      wsdlLocation = "http://test.xxd.com/yx_service/service/sysConfigWebService?wsdl",
                      endpointInterface = "com.xxdai.system.ws.SysConfigCXFService")
                      
public class SysConfigCXFServiceImpl implements SysConfigCXFService {

    private static final Logger LOG = Logger.getLogger(SysConfigCXFServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.xxdai.system.ws.SysConfigCXFService#addSConfig(java.lang.String  addSysConfig )*
     */
    public java.lang.String addSConfig(java.lang.String addSysConfig) { 
        LOG.info("Executing operation addSConfig");
        System.out.println(addSysConfig);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xxdai.system.ws.SysConfigCXFService#updateSysConfig(java.lang.String  syskey )*
     */
    public java.lang.String updateSysConfig(java.lang.String syskey) { 
        LOG.info("Executing operation updateSysConfig");
        System.out.println(syskey);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xxdai.system.ws.SysConfigCXFService#clearSysConfigAllCache(*
     */
    public java.lang.String clearSysConfigAllCache() { 
        LOG.info("Executing operation clearSysConfigAllCache");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xxdai.system.ws.SysConfigCXFService#clearSysConfigCache(java.lang.String  syskey )*
     */
    public java.lang.String clearSysConfigCache(java.lang.String syskey) { 
        LOG.info("Executing operation clearSysConfigCache");
        System.out.println(syskey);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xxdai.system.ws.SysConfigCXFService#queryObjectById(java.lang.String  queryId )*
     */
    public java.lang.String queryObjectById(java.lang.String queryId) { 
        LOG.info("Executing operation queryObjectById");
        System.out.println(queryId);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xxdai.system.ws.SysConfigCXFService#querySysConfigByKey(java.lang.String  syskey )*
     */
    public java.lang.String querySysConfigByKey(java.lang.String syskey) { 
        LOG.info("Executing operation querySysConfigByKey");
        System.out.println(syskey);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xxdai.system.ws.SysConfigCXFService#queryPageSysConfig(java.lang.String  syskey )*
     */
    public java.lang.String queryPageSysConfig(java.lang.String syskey) { 
        LOG.info("Executing operation queryPageSysConfig");
        System.out.println(syskey);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xxdai.system.ws.SysConfigCXFService#updateSConfig(java.lang.String  updateSysConfig )*
     */
    public java.lang.String updateSConfig(java.lang.String updateSysConfig) { 
        LOG.info("Executing operation updateSConfig");
        System.out.println(updateSysConfig);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
