package com.xxdai.system.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2016-10-17T11:40:36.946+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://webservice.system.xxdai.com/", name = "SysConfigCXFService")
@XmlSeeAlso({ObjectFactory.class})
public interface SysConfigCXFService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addSConfig", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.AddSConfig")
    @WebMethod
    @ResponseWrapper(localName = "addSConfigResponse", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.AddSConfigResponse")
    public java.lang.String addSConfig(
        @WebParam(name = "addSysConfig", targetNamespace = "")
        java.lang.String addSysConfig
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "UpdateSysConfig", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.UpdateSysConfig")
    @WebMethod(operationName = "UpdateSysConfig")
    @ResponseWrapper(localName = "UpdateSysConfigResponse", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.UpdateSysConfigResponse")
    public java.lang.String updateSysConfig(
        @WebParam(name = "syskey", targetNamespace = "")
        java.lang.String syskey
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "clearSysConfigAllCache", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.ClearSysConfigAllCache")
    @WebMethod
    @ResponseWrapper(localName = "clearSysConfigAllCacheResponse", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.ClearSysConfigAllCacheResponse")
    public java.lang.String clearSysConfigAllCache();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "clearSysConfigCache", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.ClearSysConfigCache")
    @WebMethod
    @ResponseWrapper(localName = "clearSysConfigCacheResponse", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.ClearSysConfigCacheResponse")
    public java.lang.String clearSysConfigCache(
        @WebParam(name = "syskey", targetNamespace = "")
        java.lang.String syskey
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryObjectById", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.QueryObjectById")
    @WebMethod
    @ResponseWrapper(localName = "queryObjectByIdResponse", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.QueryObjectByIdResponse")
    public java.lang.String queryObjectById(
        @WebParam(name = "queryId", targetNamespace = "")
        java.lang.String queryId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "querySysConfigByKey", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.QuerySysConfigByKey")
    @WebMethod
    @ResponseWrapper(localName = "querySysConfigByKeyResponse", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.QuerySysConfigByKeyResponse")
    public java.lang.String querySysConfigByKey(
        @WebParam(name = "syskey", targetNamespace = "")
        java.lang.String syskey
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryPageSysConfig", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.QueryPageSysConfig")
    @WebMethod
    @ResponseWrapper(localName = "queryPageSysConfigResponse", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.QueryPageSysConfigResponse")
    public java.lang.String queryPageSysConfig(
        @WebParam(name = "syskey", targetNamespace = "")
        java.lang.String syskey
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateSConfig", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.UpdateSConfig")
    @WebMethod
    @ResponseWrapper(localName = "updateSConfigResponse", targetNamespace = "http://webservice.system.xxdai.com/", className = "com.xxdai.system.ws.UpdateSConfigResponse")
    public java.lang.String updateSConfig(
        @WebParam(name = "updateSysConfig", targetNamespace = "")
        java.lang.String updateSysConfig
    );
}
