package com.xxdai.system.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2016-10-17T11:40:36.974+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebServiceClient(name = "SysConfigCXFServiceImplService", 
                  wsdlLocation = "http://test.xxd.com/yx_service/service/sysConfigWebService?wsdl",
                  targetNamespace = "http://impl.webservice.system.xxdai.com/") 
public class SysConfigCXFServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.system.xxdai.com/", "SysConfigCXFServiceImplService");
    public final static QName SysConfigCXFServiceImplPort = new QName("http://impl.webservice.system.xxdai.com/", "SysConfigCXFServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://test.xxd.com/yx_service/service/sysConfigWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SysConfigCXFServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://test.xxd.com/yx_service/service/sysConfigWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SysConfigCXFServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SysConfigCXFServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SysConfigCXFServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SysConfigCXFServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SysConfigCXFServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SysConfigCXFServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns SysConfigCXFService
     */
    @WebEndpoint(name = "SysConfigCXFServiceImplPort")
    public SysConfigCXFService getSysConfigCXFServiceImplPort() {
        return super.getPort(SysConfigCXFServiceImplPort, SysConfigCXFService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SysConfigCXFService
     */
    @WebEndpoint(name = "SysConfigCXFServiceImplPort")
    public SysConfigCXFService getSysConfigCXFServiceImplPort(WebServiceFeature... features) {
        return super.getPort(SysConfigCXFServiceImplPort, SysConfigCXFService.class, features);
    }

}
