
package com.xxdai.system.ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2016-10-17T11:40:36.956+08:00
 * Generated source version: 2.7.12
 * 
 */
 
public class SysConfigCXFService_SysConfigCXFServiceImplPort_Server{

    protected SysConfigCXFService_SysConfigCXFServiceImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SysConfigCXFServiceImpl();
        String address = "http://test.xxd.com/yx_service/service/sysConfigWebService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new SysConfigCXFService_SysConfigCXFServiceImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
