package com.xxdai.trade.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-04-29T17:46:40.143+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://webservice.trade.xxdai.com/", name = "TradeCXFWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface TradeCXFWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCurrMonthTradeCount", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.GetCurrMonthTradeCount")
    @WebMethod
    @ResponseWrapper(localName = "getCurrMonthTradeCountResponse", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.GetCurrMonthTradeCountResponse")
    public java.lang.String getCurrMonthTradeCount(
        @WebParam(name = "params", targetNamespace = "")
        java.lang.String params
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryTradeRequest", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.QueryTradeRequest")
    @WebMethod
    @ResponseWrapper(localName = "queryTradeRequestResponse", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.QueryTradeRequestResponse")
    public java.lang.String queryTradeRequest(
        @WebParam(name = "params", targetNamespace = "")
        java.lang.String params
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTradeDetail", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.GetTradeDetail")
    @WebMethod
    @ResponseWrapper(localName = "getTradeDetailResponse", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.GetTradeDetailResponse")
    public java.lang.String getTradeDetail(
        @WebParam(name = "params", targetNamespace = "")
        java.lang.String params
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "buyTradePack", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.BuyTradePack")
    @WebMethod
    @ResponseWrapper(localName = "buyTradePackResponse", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.BuyTradePackResponse")
    public java.lang.String buyTradePack(
        @WebParam(name = "params", targetNamespace = "")
        java.lang.String params
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTotalProfit", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.GetTotalProfit")
    @WebMethod
    @ResponseWrapper(localName = "getTotalProfitResponse", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.GetTotalProfitResponse")
    public java.lang.String getTotalProfit(
        @WebParam(name = "params", targetNamespace = "")
        java.lang.String params
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTransferingCount", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.GetTransferingCount")
    @WebMethod
    @ResponseWrapper(localName = "getTransferingCountResponse", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.GetTransferingCountResponse")
    public java.lang.String getTransferingCount(
        @WebParam(name = "params", targetNamespace = "")
        java.lang.String params
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveTradeRequest", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.SaveTradeRequest")
    @WebMethod
    @ResponseWrapper(localName = "saveTradeRequestResponse", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.SaveTradeRequestResponse")
    public java.lang.String saveTradeRequest(
        @WebParam(name = "params", targetNamespace = "")
        java.lang.String params
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTotalTradeAmount", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.GetTotalTradeAmount")
    @WebMethod
    @ResponseWrapper(localName = "getTotalTradeAmountResponse", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.GetTotalTradeAmountResponse")
    public java.lang.String getTotalTradeAmount(
        @WebParam(name = "params", targetNamespace = "")
        java.lang.String params
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "searchTradeRequest", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.SearchTradeRequest")
    @WebMethod
    @ResponseWrapper(localName = "searchTradeRequestResponse", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.SearchTradeRequestResponse")
    public java.lang.String searchTradeRequest(
        @WebParam(name = "params", targetNamespace = "")
        java.lang.String params
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAccountUsable", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.GetAccountUsable")
    @WebMethod
    @ResponseWrapper(localName = "getAccountUsableResponse", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.GetAccountUsableResponse")
    public java.lang.String getAccountUsable(
        @WebParam(name = "params", targetNamespace = "")
        java.lang.String params
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendSmsMessage", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.SendSmsMessage")
    @WebMethod
    @ResponseWrapper(localName = "sendSmsMessageResponse", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.SendSmsMessageResponse")
    public java.lang.String sendSmsMessage(
        @WebParam(name = "params", targetNamespace = "")
        java.lang.String params
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "searchTradeTransfer", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.SearchTradeTransfer")
    @WebMethod
    @ResponseWrapper(localName = "searchTradeTransferResponse", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.SearchTradeTransferResponse")
    public java.lang.String searchTradeTransfer(
        @WebParam(name = "params", targetNamespace = "")
        java.lang.String params
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkTradeTransfer", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.CheckTradeTransfer")
    @WebMethod
    @ResponseWrapper(localName = "checkTradeTransferResponse", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.CheckTradeTransferResponse")
    public java.lang.String checkTradeTransfer(
        @WebParam(name = "params", targetNamespace = "")
        java.lang.String params
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTradeRequestDetail", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.GetTradeRequestDetail")
    @WebMethod
    @ResponseWrapper(localName = "getTradeRequestDetailResponse", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.GetTradeRequestDetailResponse")
    public java.lang.String getTradeRequestDetail(
        @WebParam(name = "params", targetNamespace = "")
        java.lang.String params
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "rollbackRadeRequest", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.RollbackRadeRequest")
    @WebMethod
    @ResponseWrapper(localName = "rollbackRadeRequestResponse", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.RollbackRadeRequestResponse")
    public java.lang.String rollbackRadeRequest(
        @WebParam(name = "params", targetNamespace = "")
        java.lang.String params
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTransferOutCount", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.GetTransferOutCount")
    @WebMethod
    @ResponseWrapper(localName = "getTransferOutCountResponse", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.GetTransferOutCountResponse")
    public java.lang.String getTransferOutCount(
        @WebParam(name = "params", targetNamespace = "")
        java.lang.String params
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTotalTradeCount", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.GetTotalTradeCount")
    @WebMethod
    @ResponseWrapper(localName = "getTotalTradeCountResponse", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.GetTotalTradeCountResponse")
    public java.lang.String getTotalTradeCount(
        @WebParam(name = "params", targetNamespace = "")
        java.lang.String params
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTransferContract", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.GetTransferContract")
    @WebMethod
    @ResponseWrapper(localName = "getTransferContractResponse", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.GetTransferContractResponse")
    public java.lang.String getTransferContract(
        @WebParam(name = "params", targetNamespace = "")
        java.lang.String params
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateTradeRequestAprAndRate", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.UpdateTradeRequestAprAndRate")
    @WebMethod
    @ResponseWrapper(localName = "updateTradeRequestAprAndRateResponse", targetNamespace = "http://webservice.trade.xxdai.com/", className = "com.xxdai.trade.webservice.UpdateTradeRequestAprAndRateResponse")
    public java.lang.String updateTradeRequestAprAndRate(
        @WebParam(name = "params", targetNamespace = "")
        java.lang.String params
    );
}
