package com.xxdai.trade.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-04-29T17:46:40.201+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "TradeCXFWebServiceImplService", 
                  wsdlLocation = "http://172.16.15.66:8080/v6_webservice/service/tradeWebService?wsdl",
                  targetNamespace = "http://impl.webservice.trade.xxdai.com/") 
public class TradeCXFWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.trade.xxdai.com/", "TradeCXFWebServiceImplService");
    public final static QName TradeCXFWebServiceImplPort = new QName("http://impl.webservice.trade.xxdai.com/", "TradeCXFWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://172.16.15.66:8080/v6_webservice/service/tradeWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TradeCXFWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.16.15.66:8080/v6_webservice/service/tradeWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TradeCXFWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TradeCXFWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TradeCXFWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns TradeCXFWebService
     */
    @WebEndpoint(name = "TradeCXFWebServiceImplPort")
    public TradeCXFWebService getTradeCXFWebServiceImplPort() {
        return super.getPort(TradeCXFWebServiceImplPort, TradeCXFWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TradeCXFWebService
     */
    @WebEndpoint(name = "TradeCXFWebServiceImplPort")
    public TradeCXFWebService getTradeCXFWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(TradeCXFWebServiceImplPort, TradeCXFWebService.class, features);
    }

}
